### ISSUE TITLE
webpack mergeのエラー対応

### ISSUE THREAD

**Issue by oshanQQ** [oshanQQ/npm-self-introduction#1]
# エラー詳細
[こちらの記事]()にしたがって`npm run watch`を叩いたら、以下のようなエラーを吐いた。
```shell> npm-self-introduction@1.0.0 watch
> webpack --config webpack.dev.js --watch

[webpack-cli] Failed to load '/home/o-xian/works/o-xian/npm-self-introduction/webpack.dev.js' config
[webpack-cli] TypeError: merge is not a function
    at Object.<anonymous> (/home/o-xian/works/o-xian/npm-self-introduction/webpack.dev.js:3:18)
    at Module._compile (/home/o-xian/works/o-xian/npm-self-introduction/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/home/o-xian/works/o-xian/npm-self-introduction/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at loadConfig (/home/o-xian/works/o-xian/npm-self-introduction/node_modules/webpack-cli/lib/webpack-cli.js:1322:31)
    at /home/o-xian/works/o-xian/npm-self-introduction/node_modules/webpack-cli/lib/webpack-cli.js:1409:74
    at Array.map (<anonymous>)
```

**Comment by oshanQQ** [comment]
以下のように修正する事でエラー解消
参考：https://stackoverflow.com/questions/62846123/getting-error-from-webpack-cli-typeerror-merge-is-not-a-function-in-webpack
```js
const merge = require('webpack-merge');
-> const { merge } = require('webpack-merge');
```
